"""
NovaTech RAG Chatbot — FastAPI Backend API
==========================================

PURPOSE
-------
This file implements a pure JSON REST API for the RAG chatbot.
There is no user interface here — it is a backend service that any
frontend (Streamlit, React, mobile app, curl, Python requests) can call.

WHEN TO USE THIS FILE
---------------------
- When you want to understand how a backend API works
- When you want to build your own frontend that calls this API
- When you want to expose the chatbot as a service for other systems

HOW TO RUN LOCALLY
------------------
    uvicorn main:app --reload --port 8000

INTERACTIVE DOCS (auto-generated by FastAPI)
--------------------------------------------
    http://localhost:8000/docs      <- Swagger UI — test from browser
    http://localhost:8000/redoc     <- ReDoc UI — clean reference view

ARCHITECTURE
------------
                    ┌─────────────────────────────┐
                    │         main.py              │
                    │                              │
    POST /chat  ───►│  1. receive question         │
                    │  2. query ChromaDB           │──► _data/*.txt (indexed)
                    │  3. build prompt + context   │
                    │  4. call Groq LLM            │──► api.groq.com
                    │  5. return JSON response     │
                    └─────────────────────────────┘

DEPENDENCIES
------------
- fastapi      : web framework that handles HTTP routing and request parsing
- uvicorn      : ASGI server that runs the FastAPI app
- pydantic     : data validation — defines the shape of requests and responses
- chromadb     : in-memory vector database for semantic document search
- openai       : client library (used here to talk to Groq, not OpenAI)
- python-dotenv: loads environment variables from .env file

NOTE ON CHROMADB + FREE DEPLOYMENT
-----------------------------------
ChromaDB downloads a 79MB ONNX embedding model at first run.
This causes memory issues on free cloud tiers (512MB RAM limit).
For deployment, use streamlit_app_tfidf.py instead, which replaces
ChromaDB with lightweight TF-IDF search.
"""

import os
import uuid
import logging
from datetime import datetime
from dotenv import load_dotenv
from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI
import chromadb

# ──────────────────────────────────────
# CONFIG
# ──────────────────────────────────────

# load_dotenv() reads the .env file in the current directory and
# sets its contents as environment variables. This means
# os.getenv("groq_api_key") will find the key from .env locally,
# and from Render's environment variables in production.
load_dotenv()
GROQ_API_KEY = os.getenv("groq_api_key")

# ──────────────────────────────────────
# LOGGING
# ──────────────────────────────────────

# Configure Python's built-in logging module.
# Every log line will look like: "2026-08-12 13:33:07 | [abc123] Question: ..."
# level=INFO means we see INFO, WARNING, and ERROR messages (not DEBUG)
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s")
logger = logging.getLogger(__name__)

# ──────────────────────────────────────
# PYDANTIC SCHEMAS
# ──────────────────────────────────────
# Pydantic models define the exact shape of the data coming in and going out.
# FastAPI uses these to:
#   - Automatically validate incoming request bodies (wrong types = 422 error)
#   - Auto-generate the /docs interactive API documentation
#   - Ensure the response always has the expected fields and types

class ChatRequest(BaseModel):
    """
    Shape of the POST /chat request body.

    Example JSON the client sends:
        {"question": "What is the work from home policy?"}
    """
    question: str   # the user's question — must be a string, required

class ChatResponse(BaseModel):
    """
    Shape of the POST /chat response body.

    Example JSON the server returns:
        {
            "answer": "Employees may work from home up to 2 days per week...",
            "sources": ["company_hr_policy.txt"],
            "request_id": "a46a0fb7"
        }
    """
    answer:     str        # the LLM-generated answer
    sources:    list[str]  # list of document filenames used to answer
    request_id: str        # short unique ID for tracing this request in logs

# ──────────────────────────────────────
# RAG SETUP (runs once at server startup)
# ──────────────────────────────────────

# OpenAI client pointed at Groq's API endpoint.
# Groq is OpenAI-compatible — same SDK, different base_url and models.
# This means we get fast LLaMA inference while reusing the openai library.
client = OpenAI(api_key=GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")

# EphemeralClient = pure in-memory ChromaDB.
# Data lives only while the server is running — no files written to disk.
# We re-index documents fresh on every server start, which is fine for
# a small document set (120 chunks loads in under 1 second locally).
chroma_client = chromadb.EphemeralClient()

def load_and_index_documents() -> chromadb.Collection:
    """
    Read all .txt files from the _data/ folder, split them into paragraphs,
    and store each paragraph as a searchable document in ChromaDB.

    ChromaDB automatically converts each paragraph into a vector embedding
    using the all-MiniLM-L6-v2 model. These vectors capture the semantic
    meaning of each paragraph — not just the words, but what they mean.

    Returns:
        collection: the ChromaDB collection ready to be queried

    Raises:
        RuntimeError: if _data/ folder does not exist

    Chunking strategy — split by blank line (paragraph):
        - Each paragraph becomes one chunk
        - Chunks shorter than 50 characters are skipped (headers, blank lines)
        - Section dividers starting with "====" are skipped
        - This is "naive chunking" — simple and effective for structured documents
    """

    # Build the absolute path to _data/ relative to this file's location
    # os.path.dirname(__file__) = the folder containing main.py
    # So this always works regardless of where you run uvicorn from
    data_folder = os.path.join(os.path.dirname(__file__), "_data")

    if not os.path.exists(data_folder):
        raise RuntimeError(f"_data/ folder not found at: {data_folder}")

    # Delete the collection if it already exists (handles server restarts cleanly)
    try:
        chroma_client.delete_collection("docs")
    except Exception:
        pass  # collection didn't exist yet — that's fine

    collection = chroma_client.create_collection(name="docs")

    all_chunks    = []   # list of paragraph text strings
    all_ids       = []   # list of unique IDs — ChromaDB requires one per document
    all_metadatas = []   # list of dicts — we store the source filename here
    chunk_id      = 0    # simple incrementing counter for unique IDs

    for filename in os.listdir(data_folder):
        if not filename.endswith(".txt"):
            continue

        filepath = os.path.join(data_folder, filename)
        with open(filepath, "r") as f:
            text = f.read()

        # Split on double newline = paragraph boundary
        paragraphs = text.strip().split("\n\n")

        for para in paragraphs:
            para = para.strip()

            # Skip fragments too short to be meaningful
            if len(para) < 50:
                continue

            # Skip visual section dividers like "==============================="
            if para.startswith("===="):
                continue

            all_chunks.append(para)
            all_ids.append(f"chunk_{chunk_id}")
            all_metadatas.append({"source": filename})
            chunk_id += 1

    # Add all chunks to ChromaDB in one batch call — more efficient than one by one
    collection.add(documents=all_chunks, ids=all_ids, metadatas=all_metadatas)
    logger.info(f"Indexed {chunk_id} chunks from {data_folder}")

    return collection

# This line runs at module import time (i.e. when uvicorn loads main.py).
# By the time the first HTTP request arrives, indexing is already done.
collection = load_and_index_documents()

# ──────────────────────────────────────
# RAG FUNCTION
# ──────────────────────────────────────

def ask_rag(question: str) -> tuple[str, list[str]]:
    """
    Execute the full RAG pipeline for a given question.

    RAG = Retrieval-Augmented Generation:
      1. RETRIEVE — find the most relevant document chunks
      2. AUGMENT  — add those chunks to the LLM prompt as context
      3. GENERATE — let the LLM answer using only that context

    This grounding technique prevents hallucination — the LLM can only
    answer using text that was actually in the documents.

    Args:
        question: the user's natural language question

    Returns:
        answer:  the LLM-generated answer string
        sources: deduplicated list of source filenames used

    Step 1 — Retrieve:
        ChromaDB converts the question to an embedding vector and finds
        the 3 chunks whose vectors are most similar (cosine similarity).
        "Similar vectors" = similar meaning, not just matching words.

    Step 2 — Augment:
        The 3 chunks are joined and placed in the prompt as "Context".
        The system prompt instructs the LLM to ONLY use this context —
        not its training data. This is the key to grounded answers.

    Step 3 — Generate:
        Groq runs LLaMA 3.3 70B on the prompt and returns an answer.
        temperature=0.2 keeps answers factual and consistent (low randomness).
    """

    # Step 1 — semantic search: find top 3 most relevant chunks
    results = collection.query(query_texts=[question], n_results=3)

    # results["documents"][0] = list of 3 chunk strings
    # results["metadatas"][0] = list of 3 metadata dicts (each has "source")
    chunks  = results["documents"][0]
    sources = [m["source"] for m in results["metadatas"][0]]

    # Step 2 — build the augmented prompt
    # Join chunks with a separator so the LLM can distinguish between them
    context = "\n\n".join(chunks)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful company assistant. Answer questions using ONLY "
                "the provided context. If the context doesn't contain the answer, "
                "say 'I don't have enough information to answer this.' Be concise."
            )
        },
        {
            "role": "user",
            # The context is injected directly into the user message
            "content": f"Context:\n{context}\n\nQuestion: {question}"
        }
    ]

    # Step 3 — generate the answer
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",  # Groq-hosted LLaMA 3.3 70B
        messages=messages,
        temperature=0.2                   # low temperature = more deterministic answers
    )

    answer = response.choices[0].message.content

    # Deduplicate sources — multiple chunks may come from the same file
    return answer, list(set(sources))

# ──────────────────────────────────────
# FASTAPI APP
# ──────────────────────────────────────

# FastAPI() creates the application instance.
# title and version appear in the auto-generated /docs page.
app = FastAPI(title="NovaTech RAG Chatbot", version="1.0")

@app.get("/")
def home():
    """
    Health check endpoint.

    Used by:
    - Render to verify the service is running (it pings / periodically)
    - Developers to quickly confirm the server is live

    Returns a simple JSON dict — no RAG involved.
    """
    return {"status": "running", "message": "NovaTech RAG Chatbot is live!"}

@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Main endpoint — receives a question and returns a RAG-generated answer.

    FastAPI automatically:
    - Parses the JSON request body into a ChatRequest object
    - Validates that "question" is present and is a string
    - Returns 422 Unprocessable Entity if validation fails
    - Serializes the ChatResponse object back to JSON

    Each request gets a short random ID (first 8 chars of a UUID) so that
    log lines for the same request can be correlated easily.

    Example request:
        POST /chat
        {"question": "What is the annual leave policy?"}

    Example response:
        {
            "answer": "Employees are entitled to 18 days of annual leave...",
            "sources": ["company_hr_policy.txt"],
            "request_id": "a46a0fb7"
        }
    """
    # Generate a short unique ID for this request — used only for log tracing
    request_id = str(uuid.uuid4())[:8]

    logger.info(f"[{request_id}] Question: {request.question}")

    answer, sources = ask_rag(request.question)

    logger.info(f"[{request_id}] Sources used: {sources}")

    return ChatResponse(
        answer=answer,
        sources=sources,
        request_id=request_id
    )
